### ISSUE TITLE
cannot pull from repository: invalid auth method.

### ISSUE THREAD

**Issue by shedali** [muesli/gitomatic#4]
`gitomatic -privkey ~/.ssh/id_rsa .`
checking changes
pulling from repository...
cannot pull from repository: invalid auth method.

**Comment by muesli** [comment]
Which (kind of) url is the remote pointing to?

**Comment by shedali** [comment]
private git https remote

**Comment by atc0005** [comment]
> private git https remote

Is this the command you ran?

> `gitomatic -privkey ~/.ssh/id_rsa .`

I've not looked at the underlying code, but I would assume that by specifying the `-privkey` option you're indicating that `gitomatic` should use the provided private key for accessing the repo. If the repo is setup to use https for the remote the private key wouldn't work. I expect that if you need to use the private key for access you'll need to use `git remote set-url` to change the access method to something like `git@example.com...` instead of `https://example.com`

**Comment by shedali** [comment]
Thanks for responses. That was my assumption too but admin told me to provide my SSH pubkey to github and clone over https. I changed to ssh and it returns ```cannot pull from repository: dial tcp xx:xx:xx:xx:22: connect: operation timed out```

I'll dig some more and let you know...

**Comment by muesli** [comment]
@shedali If you're using a URL in the form of `git@github.com:muesli/gitomatic.git", you can authenticate with the `-privkey` parameter. Otherwise you can switch your remote to an https URL and use `-username` and `-password`. I don't think GitHub provides access to repositories via ssh: your error indicates ssh connections being refused by the remote.

**Comment by shedali** [comment]
thanks for your reply guys
